DROP TABLE IF EXISTS PUBLIC.users CASCADE;
DROP TABLE IF EXISTS PUBLIC.items CASCADE;
DROP TABLE IF EXISTS PUBLIC.bookings CASCADE;
DROP TABLE IF EXISTS PUBLIC.comments CASCADE;
DROP TABLE IF EXISTS PUBLIC.item_requests CASCADE;